import { useEffect } from 'react';
import { Link } from 'react-router-dom';
import { ArrowLeft } from 'lucide-react';
import { motion } from 'framer-motion';

const fadeUp = (delay = 0) => ({
  initial: { opacity: 0, y: 24 },
  animate: { opacity: 1, y: 0 },
  transition: { duration: 0.6, delay, ease: [0.25, 0.1, 0.25, 1] },
});

const clauses = [
  {
    title: '1. Acceptance of Terms',
    body: 'By accessing or using InvestSense AI ("the Platform"), you agree to be bound by these Terms and Conditions. If you do not agree to any part of these terms, you must discontinue use of the Platform immediately. These Terms apply to all visitors, registered users, and any other parties who access or use the service.',
  },
  {
    title: '2. Description of Service',
    body: 'InvestSense AI is an educational decision-support platform that provides AI-generated market analysis, stock sentiment scoring, and behavioral risk alerts. The Platform is designed to assist users in understanding market conditions and is not intended to serve as a licensed financial advisory service. All content is for informational and educational purposes only.',
  },
  {
    title: '3. Not Financial Advice',
    body: 'Nothing on this Platform constitutes financial, investment, tax, or legal advice. The analysis, signals, and recommendations generated by the AI are algorithmic in nature and are not guaranteed to be accurate, complete, or suitable for your individual financial situation. You should consult a licensed financial professional before making any investment decision. InvestSense AI accepts no liability for any financial losses arising from reliance on content provided by the Platform.',
  },
  {
    title: '4. Eligibility',
    body: 'You must be at least 17 years of age to create an account and use the Platform. By registering, you represent and warrant that you meet this age requirement and that all registration information you provide is accurate, current, and complete.',
  },
  {
    title: '5. User Account & Security',
    body: 'You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You agree to notify us immediately of any unauthorized use of your account. InvestSense AI will not be liable for any loss or damage resulting from your failure to comply with this security obligation.',
  },
  {
    title: '6. Acceptable Use',
    body: 'You agree not to use the Platform for any unlawful purpose, to attempt to gain unauthorized access to any part of the system, to introduce malicious code, to scrape or harvest data without permission, or to misrepresent your identity. Violation of these terms may result in immediate account suspension without notice.',
  },
  {
    title: '7. Intellectual Property',
    body: 'All content, design, branding, algorithms, and technology comprising InvestSense AI are the intellectual property of its creators. You are granted a limited, non-exclusive, non-transferable license to access and use the Platform solely for personal, non-commercial purposes. You may not reproduce, distribute, modify, or create derivative works from any part of the Platform without explicit written permission.',
  },
  {
    title: '8. Data Accuracy & Availability',
    body: 'Market data and news content are sourced from third-party providers and are updated periodically. InvestSense AI does not guarantee the accuracy, timeliness, or completeness of any data displayed. The Platform may experience downtime for maintenance or due to factors outside our control. We make no warranties regarding uninterrupted service availability.',
  },
  {
    title: '9. Limitation of Liability',
    body: 'To the fullest extent permitted by applicable law, InvestSense AI and its developers shall not be liable for any indirect, incidental, special, consequential, or punitive damages — including but not limited to loss of profits or investment capital — arising from your use of or inability to use the Platform.',
  },
  {
    title: '10. Modifications to Terms',
    body: 'We reserve the right to update these Terms and Conditions at any time. Changes will be posted on this page with an updated revision date. Continued use of the Platform following any changes constitutes your acceptance of the revised terms.',
  },
  {
    title: '11. Governing Law',
    body: 'These Terms are governed by and construed in accordance with the laws of the Republic of Indonesia, without regard to its conflict of law provisions. Any disputes arising under these Terms shall be subject to the exclusive jurisdiction of Indonesian courts.',
  },
  {
    title: '12. Contact',
    body: 'If you have any questions or concerns regarding these Terms and Conditions, you may contact the InvestSense AI development team through the official project channels provided in the About section of the Platform.',
  },
];

const TermsAndConditions = () => {
  useEffect(() => {
    window.scrollTo({ top: 0, behavior: 'instant' });
  }, []);

  return (
    <div className="min-h-screen bg-bg-dark text-text-main">
      <div className="fixed top-0 left-0 right-0 h-[1px] bg-card-border z-10" />

      <div className="max-w-4xl mx-auto px-6 lg:px-8 py-16 pt-20">
        <motion.div {...fadeUp(0)} className="mb-4">
          <Link
            to="/"
            className="inline-flex items-center gap-2 font-mono text-[10px] tracking-[2px] uppercase text-text-muted hover:text-accent transition-colors duration-300"
          >
            <ArrowLeft className="w-3 h-3" />
            Back to Home
          </Link>
        </motion.div>

        <motion.div {...fadeUp(0.1)} className="mb-12 pt-4">
          <p className="font-mono text-[10px] tracking-[3px] uppercase text-accent mb-4">Legal</p>
          <h1 className="font-display text-[32px] md:text-[44px] font-light text-text-main leading-tight tracking-[1px] mb-5">
            Terms & Conditions
          </h1>
          <div className="w-12 h-[1px] bg-accent mb-6" />
          <div className="flex flex-col sm:flex-row sm:items-center gap-2 sm:gap-6">
            <p className="font-body text-[14px] text-text-secondary leading-relaxed max-w-2xl">
              Please read these Terms carefully before using InvestSense AI. By accessing the Platform you agree to be bound by these terms.
            </p>
          </div>
          <p className="font-mono text-[10px] tracking-[1.5px] uppercase text-text-muted mt-4">
            Last updated: June 2026
          </p>
        </motion.div>

        <div className="space-y-6">
          {clauses.map((clause, idx) => (
            <motion.div
              key={clause.title}
              initial={{ opacity: 0, y: 16 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5, delay: 0.2 + idx * 0.04, ease: [0.25, 0.1, 0.25, 1] }}
              className="border-l-2 border-card-border pl-6 py-1 hover:border-accent/50 transition-colors duration-300"
            >
              <h2 className="font-mono text-[11px] tracking-[2px] uppercase text-text-main mb-3">
                {clause.title}
              </h2>
              <p className="font-body text-[14px] text-text-secondary leading-relaxed">
                {clause.body}
              </p>
            </motion.div>
          ))}
        </div>

        <motion.div {...fadeUp(0.5)} className="mt-16 pt-8 border-t border-card-border flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
          <p className="font-mono text-[10px] tracking-[1.5px] text-text-muted uppercase">
            © {new Date().getFullYear()} InvestSense AI. All rights reserved.
          </p>
          <div className="flex items-center gap-4">
            <Link to="/guide" className="font-mono text-[10px] tracking-[1.5px] uppercase text-text-muted hover:text-accent transition-colors duration-300">Guide</Link>
            <span className="text-card-border">·</span>
            <Link to="/privacy" className="font-mono text-[10px] tracking-[1.5px] uppercase text-text-muted hover:text-accent transition-colors duration-300">Privacy</Link>
          </div>
        </motion.div>
      </div>
    </div>
  );
};

export default TermsAndConditions;
